### ISSUE TITLE
TopTen api 오류

### ISSUE THREAD

**Issue by sunwoo0706** [theMomentTeam/the_moment_server#141]
의견남기기 페이지에서 욕설이라던지 오락성의 불편함이 올라오면, 아직은 필터링 처리 과정이 안 들어가져 있기 때문에 서버에서 직접 delete를 해줘야 하는데 그렇게 되면 `idx`가 아래와 같이 밀리게 됩니다.

<img width="363" alt="2021-06-07_17-43-42" src="https://user-images.githubusercontent.com/60869316/120986798-ed5a6900-c7b7-11eb-90bb-39b24bd68936.png">

반면 `about` 페이지에서 불편함의 수를 가져오는 api는 데이터 양을 파싱하는 로직 같습니다.

<img width="220" alt="2021-06-07_17-44-22" src="https://user-images.githubusercontent.com/60869316/120986883-0236fc80-c7b8-11eb-8a9f-08aca18eb162.png">

그래서 위와 같이 가장 최근의 불편함의 `idx`와 `about` 페이지에서 불편함의 수가 다르기 때문에 서비스를 이용하는 클라이언트의 입장에서 혼란을 줄수 있을것 같습니다.

그러니 about 페이지의 불편함 수 api를 가장 최근의 idx로 불러오는 방법 또는 다른 방법으로 수정 부탁드립니다.

**Comment by Johnjihwan** [comment]
현재 계속 1위 부분이 data parse 단계에서,
DB 에 있는 정확한 data가 res, parse가 되지 않는 현상을 발견했습니다.

해당 FE의 parse 오류인지 BE res 오류인지 로직을 확인 후 개선하도록 하겠습니다
