### ISSUE TITLE
일반 클라이언트들의 api 서버 접근

### ISSUE THREAD

**Issue by sunrabbit123** [theMomentTeam/the_moment_server#142]
![image](https://user-images.githubusercontent.com/64676070/120988208-4f679e00-c7b9-11eb-889a-a159a0449df9.png)

해당 사항을 보면 일반 유저도 해당 api서버에 쉽게 접근할 수 있는 것을 알 수 있습니다.

이러한 사항은 의도된 사항인지 여쭤보고싶습니다.

**Comment by Johnjihwan** [comment]
이슈 감사합니다.
달아주신 이슈에 대해서는 내부적으로 검토후에 답변드리겠습니다.

보안이 개선되기 전까지는 임의적인 test 용도의 api 요청을 금합니다.

**Comment by Johnjihwan** [comment]
안녕하세요, 해당 이슈에 대한 답변 드리겠습니다.
우선 저희 팀은 REST API 주소 직접 접근 req 에 대해서 [현] 치명적 보안 이슈라고 생각하지 않습니다.

우선 저희 서비스는 특정 사용자를 식별할 수 있는 Authorization 로직을 이용하지 않습니다.
하지만, 해당 이슈에 대해 추가적으로 server 접근 제한에 관한 방법을 고민하고 개선하겠습니다.
