### ISSUE TITLE
answer save 4xx error

### ISSUE THREAD

**Issue by Johnjihwan** [theMomentTeam/the_moment_server#148]
<img width="540" alt="Screen Shot 2021-06-10 at 2 11 36 PM" src="https://user-images.githubusercontent.com/67095821/121477510-e7a49380-ca02-11eb-947d-9392c06fd78d.png">

**answer content 글자 수가 많아지면 400으로 redirect 되는 현상을 발견했습니다.**

comment 남겨주세요
> @siwony  @iseolin76  @Goolgae

**Comment by siwony** [comment]
헐 혹시 글자수가 몇인지 알 수 있을까요? SpringDataJPA에서 String으로 컬럼매핑시 기본길이가 255자 입니다.
이럴경우 Entity class에서 글자수를 임의로 늘려줘야 합니다

**Comment by Johnjihwan** [comment]
ㅋㅋㅋㅋㅋㅋㅋ 오 255자 넘는 것 같기도 하고 ~

**Comment by Goolgae** [comment]
근데 그러면 왜 4xx 에러가 날까요..

**Comment by Goolgae** [comment]
@siwony 맞는것 같네요

**Comment by siwony** [comment]
몇글자로 제약조건을 추가할까요? 1000글자정도면 10포인트 기준 A4용지의 거의 반쯤 차지하는데

**Comment by Goolgae** [comment]
@siwony  저도 그 정도가 적당하다고 생각합니다!
