### ISSUE TITLE
jacoco를 disable해주세요 

### ISSUE THREAD

**Issue by siwony** [theMomentTeam/the_moment_server#150]
아직 테스트코드를 모두 작성하지 않은 상태에서 `mvn build`를 하게될경우 jacoco가 바이트코드조작을 통해 build를 실패하게됩니다.
아직까지는 jacoco를 운영상에 사용하기는 힘들것같습니다.
충분한 검증를 진행한 후 적용하는게 좋을것같습니다.

**Comment by Johnjihwan** [comment]
자코코를 삭제하라는건가요 아님 develop에서 제외하라는건가요?

**Comment by siwony** [comment]
pom.xml에서 jacoco를 비활성화 할 수 있습니다.

**Comment by Johnjihwan** [comment]
그니깐 결론적으로 모든 branch에서 비활성화 하라는건가요?

**Comment by siwony** [comment]
네

**Comment by siwony** [comment]
실수로 close 해버렸네요..
