### ISSUE TITLE
REQ에 대한 취약점 및 개선사항 요청 이슈

### ISSUE THREAD

**Issue by Johnjihwan** [theMomentTeam/the_moment_server#155]
1. HTML tag [XSS filter] 개선 및 방어
2. req json 글에 `\n` 에 관한 DB 저장 정책 논의 및 추가
3. 외부 ip 요청 막기 ex) `adsf@adsf.com/uncomfortable/write` 주소 직접 url 접근시, 잘못된 요청입니다.
4. 50x error 다른 방법으로 redirect 시키기 user에게 `절대 노출 금지`

**Comment by siwony** [comment]
외부 IP요청을 막기는 힘들것 같습니다. 프론트 서버자체가 탄력적IP가 아니라서.. csrf를 막기가 현실적으로 불가능합니다.(근데 토스는 어떻게 한것인가..)
