### ISSUE TITLE
현재 로그인한 유저정보(userEmail)를 가져오는 로직에 대한 질문

### ISSUE THREAD

**Issue by siwony** [theMomentTeam/the_moment_server#156]
`AnswerService`에 현제 로그인된 유저정보를 반환하는 `getLoginAdminEmail()` 매서드에서

`SecurityContextHolder.getContext().getAuthentication().getName()` 이와같이 로그인된 유저정보(userEmail)을 가져올수 있지만,
다음과같이 `Principal`를 `AdminDomain`으로 다운케스팅후 `instanceof`로 타입검사를 하고 `Username`(userEmail 반환)을 가져오신 이유가 궁금합니다.

`getLoginAdminEmail()`는 `AnswerService` 99번째 줄에 정의되어있습니다.
```java
    // Current userEmail 을 가져오기.
    public String getLoginAdminEmail() {
        String userEmail;
        AdminDomain principal = (AdminDomain) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
        if(principal instanceof AdminDomain) {
            userEmail = ((UserDetails)principal).getUsername();
        } else {
            userEmail = principal.toString();
        }
        return userEmail;
    }
```

추가적으로 `AdminService`  63번째줄에 `getLoginAdminEmail()`와 역할이 똑같은 `GetUserEmail()`  매서드가 정의 되어있습니다.
리펙토링이 필요해보입니다.

**Comment by Johnjihwan** [comment]
도대체 질문의 요지와 원하는 답이 뭔가요?

**Comment by siwony** [comment]
유저정보를 가져오실때 
```java
        if(principal instanceof AdminDomain) {
            userEmail = ((UserDetails)principal).getUsername();
        } else {
            userEmail = principal.toString();
        }
```
이와같이 if문을 사용하여 검증을 하는 이유가 궁금합니다.

**Comment by Johnjihwan** [comment]
현재 `AdminService.class` 테스트코드를 작성중입니다.
테스트 후 수정이 필요한 부분 그리고 변경사항 고지를 해 드리겠습니다.

**Comment by Johnjihwan** [comment]
아래와 같이 user정보를 가져올 수 있다고 합니다.
``UserDetails userDetails = (UserDetails) SecurityContextHolder.getContext().getAuthentication().getPrincipal();``

결과적으로 시원님이 제안한 아래와 같은 형식으로 바꾸는게 나을 것 같습니다.
```java
AdminDomain principal = (AdminDomain) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
        if(principal instanceof AdminDomain) {
            userEmail = ((UserDetails)principal).getUsername();
        }
```

**Comment by Johnjihwan** [comment]
## 정정하겠습니다, 시원님이 제안하신 방법은 아래와 같은 오류를 발생시킵니다.
<img width="1124" alt="Screen Shot 2021-06-13 at 1 36 15 AM" src="https://user-images.githubusercontent.com/67095821/121783123-ea141280-cbe7-11eb-8eba-c4ed201d04c6.png">

> `security` 에서 받은 `principal`을 바로 `AdminDomain`으로 cast 하지 못한다는건데요.

## 시원님이 말하신대로 한다면..
![image](https://user-images.githubusercontent.com/67095821/121783233-6575c400-cbe8-11eb-9475-8a12522d3b93.png)
> 위와 같은 방법으로 받은 principal을 .toString() 해줘야 하는 것 같습니다. 그 이유는 저희의 adminId 타입이 `String`이기 때문이죠.

**Comment by Johnjihwan** [comment]
시원님이 제안해준 방식이 `.toString()` 을 쓰면 문제가 되지 않을 것 같다만.
```java
	@Test
	void GetUserEmail(){
		//Given
		AdminDto adminDto = new AdminDto();
		String userEmail = "s20062@gsm";
		adminDto.setAdminId(userEmail);
		adminRepository.save(adminDto.toEntity());

		//When
		UsernamePasswordAuthenticationToken token = new UsernamePasswordAuthenticationToken(
				adminDto.getAdminId(),
				adminDto.getAdminPwd(),
				List.of(new SimpleGrantedAuthority("ROLE_USER")));
		SecurityContext context = SecurityContextHolder.getContext();
		context.setAuthentication(token);

		System.out.println("=================================");
		System.out.println(context);

		//then
		String currentUserEmail = adminServiceImpl.getUserEmail();
		assertEquals(currentUserEmail, "s20062@gsm");
	}
```
위와 같이 `@Test` 코드를 작성해서 ``getUserEmail()`` 로직을 테스트 해본 결과 기존 방법대로 하는게 좋을 것 같습니다.

**Comment by siwony** [comment]
오 그렇군요 신기하네요 답변 감사합니다 :)
