### ISSUE TITLE
어떤 사람이 짯는지 로직 자체가 말이 안되네요

### ISSUE THREAD

**Issue by Johnjihwan** [theMomentTeam/the_moment_server#157]
### 아래는 회원 탈퇴에 관한 로직입니다.
보면, 회원 탈퇴를 할 때, 내가 탈퇴 하고자 하는 아이디로 로그인이 돼 있는지 확인 하여, 로그인이 돼 있으면 - is ok
`SignInDto.getAdminId()` 와 `SignInDto.getAdminPwd()` 가 한 회원의 정보로 일치 한지 여부를 확인하여 - is ok
해당 adminIdx 에 `delete` 를 날리면 되는 방식으로 설계 됐어야 하는데 어떻게 생각하나요?

```java
    @Override
    public void withdrawal(SignInDto SignInDto) throws Exception {
        AdminDomain adminDomain = loginUser(SignInDto.getAdminId(), SignInDto.getAdminPwd());
        AnswerDomain answerDomain = answerService.answerFindBy(adminDomain);
        answerService.delete(answerDomain.getAnswerIdx());
        adminRepository.delete(adminDomain);
    }
```

현재 회원 탈퇴 로직을 해석하자면,
`loginUser`에 회원탈퇴를 하고자 하는`id` 와 `pw`를 넣어 그 `Admin`을 return 받고
그 `Admin`을 findby로 찾아 있는지 여부를 판별하여 있으면 delete 답변 그리고 회원탈퇴 이렇게 해석됩니다.

**Comment by siwony** [comment]
AdminDomain에서 AnswerDomain의 연관관계 매핑이 안되있어서 일단 저렇게 짰습니다.
AdminDomain과 AnswerDomain에대해 양방향 매핑을 통해 리팩토링을 하면 될것같습니다.

**Comment by Johnjihwan** [comment]
음... 시원님 `AnswerService.class`를 사용한 삭제에 대해 의문을 가진게 아니라
중간중간 회원탈퇴를 위해 검증해야할 부분이 순서가 이상하거나 부분적으로 빠져있는 부분을 얘기드린겁니다.

**Comment by siwony** [comment]
무엇이 이상하고 빠져있나요?

**Comment by Johnjihwan** [comment]
**확실히 테스트코드의 중요성을 느꼈습니다.**
<img width="550" alt="Screen Shot 2021-06-13 at 12 05 31 AM" src="https://user-images.githubusercontent.com/67095821/121780403-15443500-cbdb-11eb-9c24-ef94dcd4b9c3.png">

**해당 코드는 회원탈퇴에 관한 `@Test` 입니다. BDD 하게 test 해본결과**
1. 회원가입
2. 회원탈퇴 `ID`, `PW` set 후 
3. 탈퇴 method에 해당 signInDto를 param으로 넘겨줍니다.

시나리오 대로 하면 뜬금없는 answer에 Exception이 뜨는 걸 알 수 있습니다.
answer이 없으면 그냥 넘어가게 해둬야 하는데 없으면 Exception을 뜨게 해둔 것 같습니다.

**Comment by siwony** [comment]
AnswerDomain과 AdminDomain은 n : 1 관계인데 answerDomain을 삭제하는 로직이 말이 안되네요 근데 회원탈퇴를 위한 검증 해야할 부분에대해서 문제점을 찾지 못하겠습니다.

**Comment by siwony** [comment]
오.. 리팩토링 부탁드려요 :)

**Comment by Johnjihwan** [comment]
회원탈퇴 시나리오는 아래와 같이 되어야 합니다.
1. 회원 가입이 돼 있어야 함.
2. 삭제하고자 하는 아이디가 내가 지금 로그인 하고 있는 아이디와 일치해야 함.
3. 일치하다면 그 아이디를 findby 하여 Admin을 찾고
4. 그 Admin을 삭제해야 함

하지만 저희가 [현] 작성해둔 로직은 아래와 같습니다.
1. 내가 삭제하고자 하는 ID PW 넣기
2. 그걸로 로그인 해서 Admin return 받기 
3. 그걸 삭제하기

**Comment by siwony** [comment]
저는 한번더 로그인을 하여 확실하게 검증을 하고 싶었습니다. 이미 login이라는 method가 정의되어있어서 재사용했고요
결론적으로 어떻게 했으면 좋겠나요?

**Comment by Johnjihwan** [comment]
현재 adminService 전반적인 부분 제가 TDD 하고 있으니,
그냥 제가 수정할 것 같다는걸 말씀드리는겁니다. 변경사항은 리팩토링 후 알려드리겠습니다.

**Comment by siwony** [comment]
알겠습니다. :)
