### ISSUE TITLE
화원탈퇴 로직이 안됩니다.. ㅠㅠ

### ISSUE THREAD

**Issue by Johnjihwan** [theMomentTeam/the_moment_server#159]
<img width="587" alt="Screen Shot 2021-06-13 at 3 10 20 AM" src="https://user-images.githubusercontent.com/67095821/121785472-e5a22680-cbf4-11eb-9746-ffad4d17597a.png">

adminController login 시 token 발급되는 부분 service로 이동해야 할 것 같습니다..
그것때문에 정확한 redis token으로 test 검증을 못합니다.

**Comment by siwony** [comment]
저도 그렇게 생각합니다. 저로직을 짤때는 철이 없었죠...

**Comment by Johnjihwan** [comment]
이슈 처리 됐습니다.
