### ISSUE TITLE
x 일동안 ~ count issue

### ISSUE THREAD

**Issue by jyeonjyan** [theMomentTeam/the_moment_server#174]
<img width="500" alt="Screen Shot 2021-07-12 at 8 13 45 AM" src="https://user-images.githubusercontent.com/67095821/125212542-17d4a000-e2e9-11eb-976e-53fb0e3db653.png">

### "x 일동안 x개" 문구에서 x일 api가 문제가 생긴 것 같습니다.
- 2021.7.12 기준

**Comment by sunwoo0706** [comment]
저희 기준 날짜가 `6월 7일`이었고 달수만 밀린 `7월 7일`을 기준으로 보면 딱 맞는군요

**Comment by Johnjihwan** [comment]
핫픽스 진행중이며 오늘 내로 운영서버에 업데이트 될 예정입니다.
> https://github.com/theMomentTeam/the_moment_server/pull/175
